### ISSUE TITLE
Unfortunate design choices

### ISSUE THREAD

**Issue by marekjm** [eltrhn/ergo#2]
Hi.

You've got a cool project here! If you manage to make working with commandline arguments not painful then all the power to you.

I noticed that you thought that my `RedCLAP` library is inactive - I assume by that you mean "abandoned". By no means it is! I use it in a number of small commandline utilities I wrote for myself, and find it quite complete - that's why the development apparently stopped.
You say that some of my design choices in RedCLAP are unfortunate. Would you care to elaborate? I'd like to know what you think I can improve in my lib.

*Note: I'm reaching out through issues as I did not find your contact info. If you'd like to continue this discussion via other channels, you can reach me at marekjm [that "at" sign] ozro.pw*

**Comment by eltrhn** [comment]
Hey, thanks so much! It's probably a good thing that I don't have my email listed on my profile, because I seldom check it anyway (oops) and so this probably would have gone unnoticed ;) And I suppose that, seeing as I don't (yet?) have any users who would create issues with higher priority, this is as good a place as any to carry on a discussion. So here goes!

Honestly, first off the bat, "unfortunate" was an unfortunate word choice on my part; I was trying to find a tactful + respectful way to express my misgivings, but reading again I see that that definitely wasn't it. I'll try and reword that part, because I figure Argh too deserves a bit more respect than I gave it.

But as for the misgivings themselves, note the parenthetical in that sentence: _"within its context as a Python utility,"_ it ends. I dislike the term _[un]pythonic_ personally, as it's an annoying buzzword IMO, but in my eyes CLAP does seem like its design is slightly alien to Python -- I want to say reminiscent of Java but I don't have _that_ much experience with it so I can't be sure -- considering the type of setup that goes into developing an application with it.
Two things that stand out to me in particular are firstly that the preferred way of declaring UI is via a dictionary or an external JSON file, and secondly that a lot of the parsing process seems to be left to the developer (that is, the user of the lib). While these are **not** bad design choices in themselves, they do seem to conflict with the Python "status quo", so to speak.

As far as JSON goes, external configuration (or heck, even internal dictionary-based configuration) is not a thing I've seen any other related Python library do in this manner; what looks to be the norm instead is allowing setup to occur within a script or module itself, using Python's inbuilt facilities -- function decorators or sequential method calls or inheritance of exposed classes or whatever -- to the same effect.

The other thing, 'CLAP seems to leave a lot to the developer/user', is my impression of the setup process shown in the examples directory or the docs such as [this file](https://github.com/marekjm/clap/blob/devel/docs/hello_world/program.py). The excess of class instantiations -- first from builder.Builder (and then needing to call `.build()`, which seems to do the job that `__init__` should, and subsequently `.get()` rather than accessing a non-private `.command`) to parser.Parser to checker.RedChecker and then needing to call `RedChecker().check()` and _finally_ `Parser().parse().ui().finalise()` -- seems like it could be simply exposed to the user in a single function or method call, taking input and returning `finalise()`'s output. (Intermediary methods like `Builder().insertHelpCommand()` could instead be exposed as `__init__()` parameters, and so on).

The try/except/except/except/except/... tower around `RedChecker().check()` ([here](https://github.com/marekjm/clap/blob/devel/examples/nested.py) especially) doesn't seem too nice, either; what Python's stdlib argparse does that I agree with is it by default exits with usage info if *anything* goes wrong, and allows the user/developer to override `Parser().error()` to their liking (I kindasorta do something similar in ergo, although it's a bit easier to override). Honestly, most of the time when the user does something wrong you're gong to just want to tell them about it without much more ado, so argparse's approach seems palatable to me and it prevents the dev/user from needing to do the error-handling themselves.

----

Ergo isn't without its own unfortunate (_actually_ unfortunate) design choices either, really. For one, I'm not at all sure how to handle the creation of "groups" (which I want to be attributes of the parser object they're defined on), so I've gone from this ugliness:
```py
parser = Parser(); parser.group('grpname', [...])
@parser.grpname.etc()
```

...to this, overriding \_\_setattr\_\_ in such a way that it performs extra stuff on `ergo.Group` objects, replacing them with instances of a "private" `ergo.core._Group` class before completing the assignment. Despite being less visually-dirty, it feels almost uglier in a way due to the hidden behavior:
```py
parser = Parser(); parser.grpname = Group([...])
@parser.grpname.etc()
```
...and I'm not sure how to make it good! I also inexplicably thought (until, like, yesterday) that it was an alright idea to have parse errors print out the entirety of the program's help text rather than only (as is convention) printing out usage info... I figure stuff like this will be ironed out as I keep going, but it definitely shows that I'm not totally innocent either :)

----

Well, in any case: **Major** props to you for recognizing the usefulness of a "requires/wants/conflicts" system and implementing it before I did. That was really the thing that made me snap and go "I need to do this myself," and it kind of baffles me that more tools don't do something similar out of the box;
workarounds like [this](https://stackoverflow.com/questions/17909294/) definitely aren't pretty. It's also good to know that your lib's essentially complete; I hadn't realized this, and being fairly new to software dev myself I've never had the experience of actually finishing a project (lol) so I tend to assume stagnation and/or abandonment when I see a project whose last commit wasn't recent... the other lib I mention, argh, actually *is* somewhat abandoned (as can be seen on its issues page), which contributed to that assumption.
And of course I return this sentiment:

> If you manage to make working with commandline arguments not painful then all the power to you.

It's not an easy task (as I've found out!) and anything to make it easier is an effort worth commending :ok_hand: 

Thanks again,
Eli

**Comment by marekjm** [comment]
Wow, that was *quite* a response ;-)

Yeah, the "requires/wants/conflicts" was *the* thing I wanted from RedCLAP because I did not want to reimplement it from scratch for every util I wrote. It is incredibly useful feature, and can save you tons of time.

As for the design choices, Pythonisms and Javaisms (let me tell you that I do **not** enjoy Java in the slightest): RedCLAP is the first useful piece of software I released. In a way, I was in the same place as you - a new developer, just taking their first steps in the Free Software development, learning all the things. I wrote in a way that seemed to make sense, created a set of unit tests which consumed the API, and thought that I'm good to go...

*fast forward four years*

...and now someone comes to me saying that my lib is abandoned, when in fact last code I wrote that uses it was commited [last week](https://github.com/marekjm/issue/commit/289fb6919b93723183bd0b346215d42660338313)! So it's definitely not abandoned, it just reached a level of usefulness and completeness when I can go a year or more before I find something that can't be done easily with existing code, and must go dig in the code to add something.

The JSON configuration is something that I think was a good decision. It prevents me from getting "clever" with code, and forces me to think my designs through instead of just hacking something up. It also sets a standard - if I ever wanted to reimplement the lib in C++ or OCaml I could just consume existing interfaces instead of porting code.
The boilerplate around parsing and error handling is... ugly. But I wrote it a few years ago and have not needed to think about it since so it's not that painful, and does its job. But you do have a point about it.

As for the "(...) a lot of the parsing process seems to be left to the developer (that is, the user of the lib)." that was a deliberate design choice. I wanted a library, not a framework. I wanted RedCLAP to just parse the command line arguments, and give me a structure that I can query and get data from. This way *I* am in control, not *RedCLAP*, and I can look at the bigger picture - I defer taking action until I have seen and analysed all input.  
If I decided that every option has a callback attached to it (as you seem to do) was not something I wanted, as it just does not fit my style. But by all means - pursue that, if it fits *your* style :-) I think that writing Free Software to scratch your own itches makes for a much better results than creating solutions for everyone (maybe that's why we have so many command line handling libs).

I am incredibly happy that my lib has helped you decide to include some features, and you could analyse it to avoid making the same mistakes as I did. Learning from others, and allowing others to learn from our code by publishing it is part of why we write Free Software after all. So even if you decided that my library "sucks" and you won't use it, but will be able to write a better way as a result of being able to read my code - I count that as a success!

Cheers,
Marek.

**Comment by eltrhn** [comment]
I see. All reasonable, yup -- I can definitely get behind JSON being useful for cross-language standardization. Apologies once again for assuming the worst of the "inactivity"; it's a wonderful thing to see that a piece of software has reached a reasonably-completed state (especially after as much time + effort (5-6 years' worth!) as I see has gone into yours) and I will keep the possibility in mind in the future.

> As for the "(...) a lot of the parsing process seems to be left to the developer (that is, the user of the lib)." that was a deliberate design choice. I wanted a library, not a framework. I wanted RedCLAP to just parse the command line arguments, and give me a structure that I can query and get data from.

> If I decided that every option has a callback attached to it (as you seem to do) was not something I wanted, as it just does not fit my style.

I understand this! In saying it "leaves a lot to the developer [...]", I was referring to boilerplate and try/except stuff -- I do recognize the merit behind not having the parser take any action itself (in contrast with my callbacks-on-all-things approach) so I neglected to talk about what either package tries to do beyond the actual parsing.

I'll also be honest, ergo hasn't actually taken inspiration from much thus far. I can say I've taken "anti-inspiration" -- in that I'm actively trying to *not* do what it does -- from only one package, the stdlib's argparse, but other than that my design's really not been influenced by anything (for better or for worse) outside of my own needs or whims. I do feel it'd kind of be in poor taste to pick apart somebody else's solution, reappropriate its ideas for oneself, and then lord one's own take over it, so I've not done that... I also don't really have the patience to analyze another project's source for *detailed* comparison to my attempts. Can hardly get through my own codebase most days, really!

Now, lastly, I certainly do not think RedCLAP "sucks" ;) Your package wasn't even what got me to start developing ergo -- just argparse, and I found yours later when I started exploring the scene more -- so that I'm not using it & not taking ideas from it is a product of timing, not of my later-formed opinion towards it. You should obviously count as a success the fact that you've developed something logical & effective, rather than anything to do with another's comments toward it; if the lib works well, it works well, and that's about all that's necessary.

Cheers in return,  
Eli
